/**
 * Confidence level for extracted information
 * - high: Explicitly stated in document
 * - medium: Reasonably inferred from context
 * - low: Guessed or uncertain
 */
export type ConfidenceLevel = 'high' | 'medium' | 'low'

/**
 * Complete case brief generated by AI analysis
 */
export interface CaseBrief {
  caseType: {
    primary: string // e.g., "Divorce", "Custody", "Child Support"
    secondary?: string[] // Additional case types if multiple
    confidence: ConfidenceLevel
  }
  jurisdiction: {
    state?: string
    county?: string
    confidence: ConfidenceLevel
    source?: string // Where this was detected
  }
  parties: {
    petitioner?: PartyInfo
    respondent?: PartyInfo
    children?: ChildInfo[]
    otherParties?: PartyInfo[]
  }
  timeline: TimelineEvent[]
  keyFacts: KeyFact[]
  redFlags: RedFlag[]
  summary: string // 2-3 sentence summary
  uncertainties: Uncertainty[]
  analysisMetadata: AnalysisMetadata
}

/**
 * Information about a party in the case
 */
export interface PartyInfo {
  name?: string
  role: string
  details?: string
  confidence: ConfidenceLevel
}

/**
 * Information about a child involved in the case
 */
export interface ChildInfo {
  name?: string
  age?: number
  custody?: string
  confidence: ConfidenceLevel
}

/**
 * A significant event in the case timeline
 */
export interface TimelineEvent {
  date?: string
  description: string
  source: string // Which document this came from
  confidence: ConfidenceLevel
}

/**
 * A key fact extracted from documents
 */
export interface KeyFact {
  fact: string
  category: 'financial' | 'custody' | 'property' | 'domestic' | 'procedural' | 'other'
  importance: 'high' | 'medium' | 'low'
  source: string
  confidence: ConfidenceLevel
}

/**
 * A potential red flag or concern
 */
export interface RedFlag {
  issue: string
  severity: 'high' | 'medium' | 'low'
  details: string
  source: string
}

/**
 * An area of uncertainty that needs human review
 */
export interface Uncertainty {
  area: string
  reason: string
  needsHumanReview: boolean
}

/**
 * Metadata about the analysis process
 */
export interface AnalysisMetadata {
  documentCount: number
  totalTextLength: number
  processingTime: number // in milliseconds
  modelUsed: string
  timestamp: string // ISO date string
}

/**
 * Document with extracted text for analysis input
 */
export interface DocumentWithText {
  id: string
  filename: string
  extractedText: string
}
